require('windows').init()
require('config-reloader').init()
require('launch-apps').init()
-- require('keyboard-watcher').init()
require('wallpaper').init()
require('gitlab').init('')
hs.loadSpoon('ControlEscape'):start()
