alias axel="axel -a"
alias dotfiles="git --git-dir=$HOME/dev/.files.git/ --work-tree=$HOME"
alias dl="wget -r -l 1 -np -nd"
alias g=git
alias killaudio="sudo kill `ps -ax | grep 'coreaudiod' | grep 'sbin' |awk '{print $1}'`"
#alias lyrist="/Users/sahil/Documents/dev/lyrist/lyrist.js | less -XRq"
alias mou="open -a Mou"
alias new="open -n"
alias psgrep="ps aux | grep"
alias ql="qlmanage -p"
alias week="date +%V"
